### PR TITLE
zuul: run debian-packaging

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
It's probably blocking on one of those two lines:
```
        wazo-webhookd-init-db --user postgres
        wazo-webhookd-init-amqp
```
@fblackburn1 do you have an idea to work around that?

**Comment by fblackburn1** [comment]
> It's probably blocking on one of those two lines:
> 
> ```
>         wazo-webhookd-init-db --user postgres
>         wazo-webhookd-init-amqp
> ```
> 
> @fblackburn1 do you have an idea to work around that?

Yes it's init-amqp ... we don't have this logic on any other service using zuul and for now, I don't have workaround for that

**Comment by fblackburn1** [comment]
HAHAHAHA :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: 
It works on the first try :muscle:

**Review by sduthil — APPROVED** [review]
:+1:

**Pull request merged**
