### PR TITLE
allow enabling debug logs at runtime

### PR DESCRIPTION
**Pull request by sduthil**

### CODE REVIEW

**Review by fblackburn1 — COMMENTED** [review]
1. if `GET /config` is available, then `GET /config/debug` may not be mandatory
2. What is your opinion about something like `PUT /config/debug {"enabled": true}`
  * If you want to make another API to modify config (ex: service_discovery or clients) it would make more sense to use PUT too

But not strong opinion overall, it's should be a nice API to have

EDIT: Oh I didn't realise it was only for the runtime, then my point are more or less relevant

**Comment by sduthil** [comment]
>     1. if `GET /config` is available, then `GET /config/debug` may not be mandatory
> 
>     2. What is your opinion about something like `PUT /config/debug {"enabled": true}`
> 
> 
>     * If you want to make another API to modify config (ex: service_discovery or clients) it would make more sense to use PUT too


I agree: I think the final API would be a `PUT /config` with the same keys as in the config file, event though some config keys can't be changed at runtime (listening address for example). This `PUT /config` should persist the changes somewhere (Consul key/value?).

I'm making a second proposition with a partial `PUT /config` that only accepts `debug: true/false`.

**Comment by fblackburn1** [comment]
@sduthil can we close this PR in favor of https://github.com/wazo-platform/wazo-webhookd/pull/103 ?

**Comment by sduthil** [comment]
Yes, absolutely, I forgot about this PR. Thanks!

**Pull request closed without merging**
