### PR TITLE
Ensure truncated log are string

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by fblackburn1** [comment]
Can you investigate to make the test more robust? (maybe in another PR)

**Comment by sileht** [comment]
> Can you investigate to make the test more robust? (maybe in another PR)

It's just the gate that seems to slow, I will add some more tries or intervals. We see in docker logs the consumer is declared just after the sentinel have finished.

```
webhookd_1            | 2019-11-06 15:25:46,376 [1] (DEBUG) (wazo_webhookd.bus): Subscribing new callback to events ['test'] (uuid: 85a05eff-500f-4029-9244-cd898d662abe)
webhookd_1            | 2019-11-06 15:25:46,379 [1] (INFO) (flask.app): response: (172.30.0.1) POST https://localhost:32846/1.0/subscriptions 201
webhookd_1            | 2019-11-06 15:25:46,379 [1] (DEBUG) (wazo_webhookd.rest_api): request data: b'{"name": "test", "service": "http", "config": {"url": "http://test.example.com?test_case=test_given_non_user_subscription_when_user_delete_http_subscription_then_404", "method": "get"}, "events": ["test"], "events_user_uuid": "b17d9f99-fcc7-4257-8e89-3d0e36e0b48d"}'
webhookd_1            | 2019-11-06 15:25:46,379 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"events_user_uuid": "b17d9f99-fcc7-4257-8e89-3d0e36e0b48d", "config": {"method": "get", "url": "http://test.example.com?test_case=test_given_non_user_subscription_when_user_delete_http_subscription_then_404"}, "service": "http", "owner_user_uuid": null, "name": "test", "events_wazo_uuid": null, "events": ["test"], "uuid": "85a05eff-500f-4029-9244-cd898d662abe", "owner_tenant_uuid": "f0fe8e3a-2d7a-4dd7-8e93-8229d51cfe04"}'
webhookd_1            | 2019-11-06 15:25:46,743 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:46,743 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:46,743 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:47,267 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:47,268 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:47,268 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:47,792 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:47,793 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:47,793 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:48,317 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:48,318 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:48,318 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:48,843 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:48,843 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:48,844 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:49,368 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:49,369 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:49,369 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:49,893 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:49,894 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:49,894 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:50,418 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:50,418 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:50,419 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:50,943 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:50,944 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:50,944 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:51,469 [1] (INFO) (flask.app): response: (172.30.0.1) GET https://localhost:32846/1.0/sentinel 200
webhookd_1            | 2019-11-06 15:25:51,469 [1] (DEBUG) (wazo_webhookd.rest_api): request data: ""
webhookd_1            | 2019-11-06 15:25:51,469 [1] (DEBUG) (wazo_webhookd.rest_api): response body: b'{"called": false, "consumers": []}'
webhookd_1            | 2019-11-06 15:25:51,851 [1] (INFO) (kombu.mixins): Connected to amqp://guest:**@rabbitmq:5672//
webhookd_1            | 2019-11-06 15:25:51,854 [1] (DEBUG) (wazo_webhookd.bus): Adding consumer (uuid: 85a05eff-500f-4029-9244-cd898d662abe)
```

**Pull request merged**
